services:

  #################
  # GitLab Server
  #################
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab.yourdomain.com
    container_name: gitlab
    ports:
      - "2224:22"
      - "8080:80"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.yourdomain.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    volumes:
      - ./mnt/nfs/gitlab/config:/etc/gitlab
      - ./mnt/nfs/gitlab/logs:/var/log/gitlab
      - ./mnt/nfs/gitlab/data:/var/opt/gitlab

  # ################
  # # Harbor (Full)
  # ################
  # registry:
  #   image: goharbor/registry-photon:v2.13.0
  #   restart: always
  #   volumes:
  #     - ./mnt/nfs/harbor/data:/storage

  # registryctl:
  #   image: goharbor/harbor-registryctl:v2.13.0
  #   restart: always

  # harbor-db:
  #   image: goharbor/harbor-db:v2.13.0
  #   restart: always
  #   volumes:
  #     - ./mnt/nfs/harbor/db:/var/lib/postgresql/data

  # redis:
  #   image: goharbor/redis-photon:v2.13.0
  #   restart: always
  #   volumes:
  #     - ./mnt/nfs/harbor/redis:/data

  # harbor-core:
  #   image: goharbor/harbor-core:v2.13.0
  #   restart: always
  #   volumes:
  #     - ./mnt/nfs/harbor/data:/data

  # portal:
  #   image: goharbor/harbor-portal:v2.13.0
  #   restart: always

  # jobservice:
  #   image: goharbor/harbor-jobservice:v2.13.0
  #   restart: always
  #   volumes:
  #     - ./mnt/nfs/harbor/job_logs:/var/log/jobs

  # trivy:
  #   image: goharbor/trivy-adapter-photon:v2.13.0
  #   restart: always
  #   volumes:
  #     - ./mnt/nfs/harbor/trivy:/home/scanner/.cache

  # nginx-harbor:
  #   image: goharbor/nginx-photon:v2.13.0
  #   restart: always
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - ./mnt/nfs/harbor/nginx:/etc/nginx

  #################
  # Portainer
  #################
  portainer:
    image: portainer/portainer-ce
    restart: always
    container_name: portainer
    ports:
      - "8082:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mnt/nfs/portainer/data:/data

  #################
  # Nginx Reverse Proxy
  #################
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   restart: always
  #   ports:
  #     - "80:80"
  #     # - "443:443"  # Enable if using SSL
  #   volumes:
  #     - /mnt/nfs/nginx/conf.d:/etc/nginx/conf.d
  #     - /mnt/nfs/certs:/etc/nginx/certs:ro  # optional SSL
  #   depends_on:
  #     - gitlab
  #     - nginx-harbor
  #     - portainer
networks:
  ghp:
    name: ghp
    driver: bridge