stages:
  - compile
  - sonar
  - build
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dtarget.os=linux -Dtarget.ws=gtk -Dtarget.arch=x86_64 -Dp2.repo.zk=file:/cache/binary.file/p2.zk/10.0.1 -Dp2.repo.repackaged=file:/cache/binary.file/p2.repackaged/12.0.0 -Dp2.repo.jasperstudio=file:/cache/binary.file/p2.repackaged/jasperstudio/6.17.0"

default:
  image:
    name: docker
    entrypoint: [""]
  tags:
    - docker-runner

compile:
  stage: compile
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .m2/repository
  script:
    - apk add git openjdk17 maven
    - rm -rf /cache/temp
    - mkdir /cache/temp && cp -r * /cache/temp
    - cd /cache/temp
    - |
      if [ ! -d "/cache/binary.file" ]; then
        git clone --depth=1 --branch master --single-branch https://github.com/idempiere/binary.file.git /cache/binary.file
      else
        echo "binary.file already exists, skipping clone"
      fi
    - git clone --depth=1 --branch massup-12-demo --single-branch https://$BITTOKEN@bitbucket.org/forca/idempiere-forca.git idempiere-forca
    # - git clone --depth=1 --branch release-12 --single-branch https://github.com/idempiere/idempiere.git idempiere-forca
    - git clone --depth=1 --branch massup-12-demo --single-branch https://$BITTOKEN@bitbucket.org/forca/plugins-erp.git plugins-erp
    - cd idempiere-forca
    - mvn clean verify -DskipTests -T 1C
    - mkdir -p ../idempiere-server
    - cp -r org.idempiere.p2/target/products/org.adempiere.server.product/linux/gtk/x86_64/* ../idempiere-server
    # - cp ../Dockerfile ../idempiere-server/Dockerfile
    # - cp ../docker-entrypoint.sh ../idempiere-server/docker-entrypoint.sh
    # - cd ../idempiere-server/
    # - docker build -t forca-erp:latest .

compile-offline:
  stage: compile
  when: manual
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .m2/repository
  script:
    - apk add git openjdk17 maven
    - rm -rf /cache/temp
    - mkdir /cache/temp && cp -r * /cache/temp
    - cd /cache/temp
    - |
      if [ ! -d "/cache/binary.file" ]; then
        git clone --depth=1 --branch master --single-branch https://github.com/idempiere/binary.file.git /cache/binary.file
      else
        echo "binary.file already exists, skipping clone"
      fi
    - git clone --depth=1 --branch massup-12-demo --single-branch https://$BITTOKEN@bitbucket.org/forca/idempiere-forca.git idempiere-forca
    # - git clone --depth=1 --branch release-12 --single-branch https://github.com/idempiere/idempiere.git idempiere-forca
    - git clone --depth=1 --branch massup-12-demo --single-branch https://$BITTOKEN@bitbucket.org/forca/plugins-erp.git plugins-erp
    - cd idempiere-forca
    - sed -i '/https:\/\/download\.eclipse\.org/d' org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
    - sed -i '/<locations>/a\
      <location type="InstallableUnit" includeAllPlatforms="true" includeMode="slicer" includeSource="true" includeConfigurePhase="true">\
        <repository location="file:../binary.file/p2.repackaged/12.0.0"/>\
      </location>' org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
    - mvn clean verify -DskipTests -T 1C
    - mkdir -p ../idempiere-server
    - cp -r org.idempiere.p2/target/products/org.adempiere.server.product/linux/gtk/x86_64/* ../idempiere-server
    # - cp ../Dockerfile ../idempiere-server/Dockerfile
    # - cp ../docker-entrypoint.sh ../idempiere-server/docker-entrypoint.sh
    # - cd ../idempiere-server/
    # - docker build -t forca-erp:latest .    
    
sonar:
  stage: sonar
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
      - .m2/repository
  script:
    - apk add git openjdk17 maven
    - cd /cache/temp/idempiere-forca
    - >
      mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar
      -Dsonar.projectKey=${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}
      -Dsonar.sources=. -Dsonar.projectName="${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}"
      # -Dsonar.exclusions=**/I_*.java,**/X_*.java
      -Dsonar.host.url=http://10.0.2.21:8081
      # -DmaterializeProduct=none
      # -DassembleRepository=none
      # -Dsonar.sourceEncoding=UTF-8
      # -Dsonar.scanner.javaOpts="-Xmx6g"
      # -Dsonar.issue.ignore.multicriteria=e1,e2
      # -Dsonar.issue.ignore.multicriteria.e1.ruleKey=java:S3252
      # -Dsonar.issue.ignore.multicriteria.e1.resourceKey=**/*.java
      # -Dsonar.issue.ignore.multicriteria.e2.ruleKey=java:S117
      # -Dsonar.issue.ignore.multicriteria.e2.resourceKey=**/*.java
      -Dsonar.token=$SONARTOKEN
      -Dsonar.qualitygate.wait=true

build:
  stage: build
  script:
    - cd /cache/temp/idempiere-server 
    - docker build -t forca-erp:latest .
    
deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d --force-recreate
